default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1


development:
  <<: *default
  database: pickybitz_development


test:
  <<: *default
  database: pickybitz_test


production:
  <<: *default
  adapter: postgresql
  database: pickybitz_production
  username: deploy
  password: deploy123
